name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the stack
        run: docker compose up --quiet-pull --no-color --remove-orphans --abort-on-container-failure --exit-code-from seed
