name: ci

on:
  push:
  pull_request:

jobs:
  dotnet-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

  docker-ci:
    runs-on: ubuntu-latest
    needs: dotnet-ci
    steps:
      - uses: actions/checkout@v4
      - name: Build the stack
        run: DOCKER_BUILDKIT=1 docker compose up --quiet-pull --no-color --remove-orphans --exit-code-from seed
